name: CI & Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write  # нужно для того, чтобы пушить теги/коммиты

jobs:
  test-build-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # нужно для анализа коммитов commitizen

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install hatch uv commitizen
          uv pip install -e ".[dev]"

      - name: Run tests
        run: uv run pytest -q

      - name: Bump version
        id: bump
        run: |
          cz bump --yes --changelog
          echo "version=$(cz version --project)" >> $GITHUB_OUTPUT

      - name: Commit and push version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pyproject.toml CHANGELOG.md
          git commit -m "chore(release): ${{ steps.bump.outputs.version }}"
          git tag v${{ steps.bump.outputs.version }}
          git push origin HEAD:main --tags

      - name: Build package
        run: hatch build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
